# Generated by Django 3.1.6 on 2021-05-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snod', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairsofoptionstruesnod',
            name='quasi_level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
