# Generated by Django 3.1.6 on 2021-05-13 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snod', '0002_pairsofoptionstruesnod_in_result_and_not_comparable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pairsofoptionstruesnod',
            name='winner_option',
        ),
    ]
