# Generated by Django 3.1.6 on 2021-05-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairsofoptionspark',
            name='quasi_level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
