# Generated by Django 3.1.6 on 2021-05-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacom', '0003_auto_20210523_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='valueofperfectalternativepark',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
