# Generated by Django 3.1.6 on 2021-05-17 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_model', to=settings.AUTH_USER_MODEL),
        ),
    ]
