# Generated by Django 3.1.6 on 2021-05-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='option',
            name='quasi_order_original_snod',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='option',
            name='quasi_order_pacom',
            field=models.IntegerField(default=-1),
        ),
    ]
