# Generated by Django 3.1.6 on 2021-05-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_auto_20210509_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
