# Generated by Django 3.1.6 on 2021-05-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_model_quasi_max_order_pacom'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
