# Generated by Django 3.1.6 on 2021-05-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_model_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='is_searching_pacom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='model',
            name='is_searching_snod',
            field=models.BooleanField(default=False),
        ),
    ]
