# Generated by Django 3.1.6 on 2021-05-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_auto_20210509_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='graph_snod',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='quasi_max_order_snod',
            field=models.IntegerField(default=0),
        ),
    ]
