# Generated by Django 3.1.6 on 2021-05-11 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_auto_20210510_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='id_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model', to='model.model'),
        ),
    ]
