# Generated by Django 3.1.6 on 2021-05-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0006_auto_20210511_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='has_incomparable_pairs_result_pacom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='model',
            name='has_incomparable_pairs_result_snod',
            field=models.BooleanField(default=False),
        ),
    ]
