# Generated by Django 3.1.6 on 2021-05-14 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeModification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ModelModification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.model')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modification.typemodification')),
            ],
        ),
        migrations.CreateModel(
            name='CriterionModification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('for_snod', models.BooleanField(default=False)),
                ('for_pacom', models.BooleanField(default=False)),
                ('criterion', models.ManyToManyField(to='model.Criterion', verbose_name='Исходный критерий')),
            ],
        ),
    ]
