# Generated by Django 3.1.6 on 2021-05-16 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
        ('modification', '0004_criterionmodification_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairsOfOptionsTrueSNOD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('already_find_winner', models.BooleanField(default=False)),
                ('is_not_comparable', models.BooleanField(default=False)),
                ('flag_winner_option', models.IntegerField(default=-1)),
                ('flag_not_compared', models.BooleanField(default=True)),
                ('in_result_and_not_comparable', models.BooleanField(default=False)),
                ('quasi_level', models.PositiveIntegerField(default=0)),
                ('model_m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modification.modelmodification')),
                ('option_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_option_1_modification', to='model.option')),
                ('option_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_option_2_modification', to='model.option')),
            ],
        ),
    ]
