# Generated by Django 3.1.6 on 2021-05-16 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
        ('modification', '0005_pairsofoptionstruesnod'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PairsOfOptionsTrueSNOD',
            new_name='ModificationPairsOfOptions',
        ),
    ]
