# Generated by Django 3.1.6 on 2021-05-16 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
        ('modification', '0006_auto_20210516_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModificationOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quasi_order_pacom', models.IntegerField(default=-1)),
                ('quasi_order_original_snod', models.IntegerField(default=-1)),
                ('model_m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modification.modelmodification')),
                ('parent_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.option')),
            ],
        ),
    ]
