# Generated by Django 3.1.6 on 2021-05-16 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modification', '0008_auto_20210516_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modificationvalue',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modification.modificationoption'),
        ),
    ]
