# Generated by Django 3.1.6 on 2021-05-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modification', '0009_auto_20210516_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelmodification',
            name='already_find_winner',
            field=models.BooleanField(default=False),
        ),
    ]
