# Generated by Django 3.1.6 on 2021-05-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modification', '0010_modelmodification_already_find_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='modificationoption',
            name='already_fill_values',
            field=models.BooleanField(default=False),
        ),
    ]
