# Generated by Django 3.1.6 on 2021-02-12 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('direction', models.BooleanField()),
                ('max', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_demo', models.BooleanField()),
                ('name', models.CharField(max_length=255)),
                ('id_winner_option_shnur', models.IntegerField(null=True)),
                ('id_winner_option_many', models.IntegerField(null=True)),
                ('time_shnur', models.CharField(max_length=255)),
                ('time_answer_shnur', models.CharField(max_length=255)),
                ('time_many', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('id_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spbpu.model')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('id_criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spbpu.criterion')),
                ('id_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spbpu.option')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PairsOfOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spbpu.model')),
                ('id_option_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_option_1', to='spbpu.option')),
                ('id_option_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_option_2', to='spbpu.option')),
                ('winner_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_option', to='spbpu.option')),
                ('winner_option_many', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_option_many', to='spbpu.option')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=1000)),
                ('answer', models.CharField(max_length=255)),
                ('id_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spbpu.model')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair', to='spbpu.pairsofoptions')),
            ],
        ),
        migrations.AddField(
            model_name='criterion',
            name='id_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spbpu.model'),
        ),
    ]
