# Generated by Django 3.1.6 on 2021-02-21 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spbpu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairsOfOptionsPARK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('already_range', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='model',
            name='id_winner_option_park',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='RangeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spbpu.criterion')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spbpu.option')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spbpu.pairsofoptionspark')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spbpu.value')),
            ],
        ),
        migrations.AddField(
            model_name='pairsofoptionspark',
            name='id_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spbpu.model'),
        ),
        migrations.AddField(
            model_name='pairsofoptionspark',
            name='id_option_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_park_option_1', to='spbpu.option'),
        ),
        migrations.AddField(
            model_name='pairsofoptionspark',
            name='id_option_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_park_option_2', to='spbpu.option'),
        ),
        migrations.AddField(
            model_name='pairsofoptionspark',
            name='winner_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='park_winner_option', to='spbpu.option'),
        ),
    ]
