# Generated by Django 3.1.6 on 2021-02-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spbpu', '0002_auto_20210221_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rangevalue',
            name='value',
            field=models.IntegerField(null=True),
        ),
    ]
