# Generated by Django 3.1.6 on 2021-02-28 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spbpu', '0003_auto_20210228_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueOfPerfectAlternativePARK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(null=True)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spbpu.criterion')),
                ('perfect_alternative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spbpu.pairsofoptionspark')),
            ],
        ),
        migrations.CreateModel(
            name='PerfectAlternativePARK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spbpu.pairsofoptionspark')),
            ],
        ),
    ]
