# Generated by Django 3.1.6 on 2021-02-28 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spbpu', '0004_perfectalternativepark_valueofperfectalternativepark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valueofperfectalternativepark',
            name='perfect_alternative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spbpu.perfectalternativepark'),
        ),
    ]
