# Generated by Django 3.1.6 on 2021-03-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spbpu', '0006_historyanswerpark_setofoptions_valueofsetofoptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valueofsetofoptions',
            name='set_option',
        ),
        migrations.RemoveField(
            model_name='valueofsetofoptions',
            name='value',
        ),
        migrations.RemoveField(
            model_name='historyanswerpark',
            name='set_option_1',
        ),
        migrations.RemoveField(
            model_name='historyanswerpark',
            name='set_option_2',
        ),
        migrations.RemoveField(
            model_name='historyanswerpark',
            name='winner_set',
        ),
        migrations.AddField(
            model_name='historyanswerpark',
            name='filename',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SetOfOptions',
        ),
        migrations.DeleteModel(
            name='ValueOfSetOfOptions',
        ),
    ]
