# Generated by Django 3.1.6 on 2021-03-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spbpu', '0007_auto_20210301_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairsofoptionspark',
            name='init_file',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='HistoryAnswerPARK',
        ),
    ]
