# Generated by Django 3.1.6 on 2021-03-05 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spbpu', '0008_auto_20210301_0804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='first_name',
            new_name='username',
        ),
    ]
