# Generated by Django 3.1.6 on 2021-03-17 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spbpu', '0009_auto_20210305_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairsofoptionspark',
            name='compensable_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='park_compensable_option', to='spbpu.option'),
        ),
    ]
