# Generated by Django 3.1.6 on 2021-03-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spbpu', '0012_auto_20210318_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pairsofoptionspark',
            name='winners_option',
        ),
        migrations.AddField(
            model_name='option',
            name='quasi_order_pacom',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pairsofoptionspark',
            name='already_find_winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pairsofoptionspark',
            name='is_not_comparable',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='WinnerOptionsPACOM',
        ),
    ]
