# Generated by Django 3.1.6 on 2021-03-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spbpu', '0015_historyanswerpacom'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='number_of_questions_pacom',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='model',
            name='time_answer_pacom',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
