# Generated by Django 3.1.6 on 2021-03-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spbpu', '0017_pairsofoptionspark_flag_winner_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='number_of_incomparable',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='model',
            name='number_of_pairs',
            field=models.IntegerField(default=0),
        ),
    ]
