# Generated by Django 3.1.6 on 2021-03-25 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spbpu', '0018_auto_20210325_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsPACOM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_mode', models.BooleanField(default=False)),
                ('larichev_question', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='model',
            name='id_settings_pacom',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='spbpu.settingspacom'),
        ),
    ]
