# Generated by Django 3.1.6 on 2021-03-27 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spbpu', '0019_auto_20210325_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='id_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spbpu.userprofile'),
            preserve_default=False,
        ),
    ]
