# Generated by Django 3.1.6 on 2021-03-27 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spbpu', '0020_model_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='id_user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
