# Generated by Django 3.1.6 on 2021-04-03 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spbpu', '0023_auto_20210329_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairsOfOptionsTrueSNOD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('already_find_winner', models.BooleanField(default=False)),
                ('is_not_comparable', models.BooleanField(default=False)),
                ('flag_winner_option', models.IntegerField(default=-1)),
                ('id_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spbpu.model')),
                ('id_option_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_option_1_true_snod', to='spbpu.option')),
                ('id_option_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_option_2_true_snod', to='spbpu.option')),
                ('winner_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_option_true_snod', to='spbpu.option')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryAnswerTrueSNOD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=1000)),
                ('answer', models.CharField(max_length=255)),
                ('id_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spbpu.model')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_true_snod', to='spbpu.pairsofoptionstruesnod')),
            ],
        ),
    ]
