# Generated by Django 3.1.6 on 2021-04-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spbpu', '0024_historyanswertruesnod_pairsofoptionstruesnod'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='already_find_winner_SNOD',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='model',
            name='number_of_incomparable_snod',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='model',
            name='number_of_pairs_snod',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='model',
            name='number_of_questions_snod',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='model',
            name='time_answer_snod',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
