# Generated by Django 3.1.6 on 2021-04-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spbpu', '0025_auto_20210404_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairsofoptionstruesnod',
            name='flag_not_compared',
            field=models.BooleanField(default=True),
        ),
    ]
