# Generated by Django 3.1.6 on 2021-04-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spbpu', '0026_pairsofoptionstruesnod_flag_not_compared'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='quasi_order_original_snod',
            field=models.IntegerField(default=0),
        ),
    ]
