# Generated by Django 3.1.6 on 2021-04-07 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spbpu', '0027_option_quasi_order_original_snod'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsOrigianlSNOD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_mode', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='model',
            name='id_settings_original_snod',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='spbpu.settingsorigianlsnod'),
        ),
    ]
