# Generated by Django 3.1.6 on 2021-04-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spbpu', '0028_auto_20210407_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='number_repeated_questions_snod',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
